create table tb_clientealuno
(
    rm               bigint generated by default as identity,
    nome             Varchar(100),
    turma			 varchar(20),	
    cpf              varchar(20),
    rg 				 varchar(20),
    dataNascimento   timestamp not null,
    primary key (rm)
)