create table tb_clientealuno (id_clientealuno bigint not null, 
							  cpf varchar(255), 
							  data_nascimento timestamp, 
							  is_cliente boolean,
							  nome varchar(255), 
							  rg varchar(255), 
							  rm integer, 
							  turma varchar(255), 
							  cartao_id bigint, 
							  primary key (id_clientealuno))