create table tb_clientealuno
(
    rm               bigint generated by default as identity,
    nome             boolean,
    cpf              varchar(255),
    rg 				 timestamp,
    dataNascimento   timestamp not null,
    primary key (id)
)