spring:
  datasource:
    url: jdbc:h2:tcp://localhost/mem:userdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: teste2
input:
  file: D:\FIAP-AULAS\Spring\trabalho\fiap-spring\batch\src\main\resources\lista_alunos1.txt
