spring:
  datasource:
    url: jdbc:h2:~/userdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: "/h2" 
server:
  port: 8082
jwt:
  secret: fiapSecr3tfiapSecr3tfiapSecr3tfiapSecr3tfiapSecr3t
  expiration: 5