server:
  port: 8089

springfox:
  documentation:
    swagger-ui:
      enabled: true

spring:
  datasource:
    url: jdbc:h2:F:\Mba\Spring\db\transactiondb;DB_CLOSE_ON_EXIT=FALSE
    username: transaction
    password: spring
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: pride.dalian@gmail.com
    password: clgbodjdoorwxqop
    protocol: smtp
    smtp:
      auth: true
      starttls:
        enable: true
    properties:
      mail:
        to: williankaza@hotmail.com
