server:
  port: 8089

springfox:
  documentation:
    swagger-ui:
      enabled: true

spring:
  datasource:
    url: jdbc:h2:C:/dev/db/dbbatchspringfinal;DB_CLOSE_ON_EXIT=FALSE
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: 
    password: 
    protocol: smtp
    properties:
      mail:
        to: 
      smtp:
        auth: true
        connectiontimeout: 5000
        timeout: 5000
        writetimeout: 5000
        starttls:
          enable: true
securityRemote: http://localhost:8082/