server:
  port: 8088
  servlet:
    context-path: /clientealuno-app

fiapspring:
    debug: true
    
springfox:
  documentation:
    swagger-ui:
      enabled: true
   

spring:
  datasource:
    url: jdbc:h2:D:\fiapspring;DB_CLOSE_ON_EXIT=FALSE
    username: teste
    password: teste    tomcat:      test-on-borrow: true
      validation-query: SELECT 1
    sql-script-encoding: UTF-8
  jpa:
    show-sql: true
    hibernate:      naming:        implicit-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    open-in-view: true
  h2:
    console:
      enabled: true
    
         
securityRemote: http://localhost:8082/
#http://localhost:8088/h2-console 
#security:
#  user:
#    name: sara
#    password: senha
#    roles: ADMIN