server:
  port: 8088
  servlet:
    context-path: /clientealuno-app
    
springfox:
  documentation:
    swagger-ui:
      enabled: true

spring:
  datasource:
    url: jdbc:h2:mem:userdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: teste2
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
      
         
securityRemote: http://localhost:8082/
#http://localhost:8088/h2-console 
#security:
#  user:
#    name: sara
#    password: senha
#    roles: ADMIN