server:
  port: 8088
  servlet:
    context-path: /clientealuno-app

fiapspring:
    debug: true
    
springfox:
  documentation:
    swagger-ui:
      enabled: true
   

spring:
  datasource:
    url: jdbc:h2:D:\fiapspring;DB_CLOSE_ON_EXIT=FALSE
    username: teste
    password: teste
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
  devtools:    add-properties: true
  
         
securityRemote: http://localhost:8082/
#http://localhost:8088/h2-console 
#security:
#  user:
#    name: sara
#    password: senha
#    roles: ADMIN